name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_IMAGE }} -f ai-dockerfile .

    - name: Push Docker image to GCR
      run: docker push ${{ secrets.DOCKER_IMAGE }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg

    - name: Add Google Cloud SDK package source
      run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    
    - name: Update package lists
      run: sudo apt-get update

    - name: Install gke-gcloud-auth-plugin
      run: sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Set up GKE credentials
      run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    - name: Deploy to GKE
      run: |
        kubectl apply -f ai-deployment.yaml

